import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Table from '../componentes/tabla'
import Form from '../componentes/form'

export default function Home() {
  return (
    <div >
      <Head>
        <title>CRUDsito</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className='container-fluid row ' id='navbar'>
          <h1 className='text-center'>Agregar empleados</h1>

        </div>
        <div className='container-fluid row mt-5' id='cuerpo'>
          <div className='row'>
            <div className='col-3 pt-3 text-center'>
              <button className="btn btn-primary " type="submit">Agregar usuario</button>
            </div>
            <div className='col-6'>
              <didv>
                <Form />
              </didv>
              <div>
                <Table />
              </div>

            </div>
            <div className='col-3'>

            </div>
          </div>
        </div>


      </div>

    </div>
  )
}
